-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
	name = "jetbrains",
	match = {
		class = "^(jetbrains-.*)",
		title = "^win.*",
	},
	no_initial_focus = true,
	float = true,
})

hl.window_rule({
	name = "jetbrains2",
	match = {
		class = ".*",
	},
	suppress_event = "maximise",
})

hl.window_rule({
	name = "other_jetbrains_stuff",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
})

hl.window_rule({
	name = "freeCad",
	match = {
		class = "FreeCAD",
	},
	no_initial_focus = true,
})

hl.window_rule({
	name = "Dolphin",
	match = {
		class = "Dolphin",
	},
	no_initial_focus = true,
})

hl.window_rule({
	name = "goland",
	match = {
		class = "^(jetbrains-goland)",
		title = "^win.*",
	},
	no_initial_focus = true,
	float = true,
})

hl.window_rule({
	name = "goland2",
	match = {
		class = "^(jetbrains-goland)",
		title = "^$",
		initial_title = "^$",
	},
	no_initial_focus = true,
	float = true,
})

hl.window_rule({
	name = "idk",
	match = {
		class = ".*",
	},
	suppress_event = "maximize",
})

hl.window_rule({
	name = "idk2",
	match = {
		focus = false,
		class = "^$",
		title = "^$",
		xwayland = 1,
		float = true,
		fullscreen = false,
		pin = false,
	},
})

hl.window_rule({
	name = "godot_main",
	match = {
		class = "^(Godot)$",
		title = "^(Godot)(.*)$",
	},
})

hl.window_rule({
	name = "godot_other",
	match = {
		class = "^(Godot)$",
		title = "^(?!Godot)(.*)$",
	},
})

-- Main Exiled Exchange window
hl.window_rule({
	name = "exiled-exchange",
	match = {
		class = "^(exiled-exchange-2)$",
	},
	no_blur = true,
})

-- exiled exchange
hl.bind("CTRL + d", hl.dsp.pass({ window = "class:^(exiled-exchange-2)$" }))
hl.bind("ALT + e", hl.dsp.pass({ window = "class:^(exiled-exchange-2)$" }))
hl.bind("SHIFT + SPACE", hl.dsp.pass({ window = "class:^(exiled-exchange-2)$" }))

--###############
--## MONITORS ###
--###############
-- Source: ./monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors")

--##################
--## MY PROGRAMS ###
--##################
-- Source: ./programs.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("programs")

--##################
--## KEYBINDINGS ###
--##################
-- See https://wiki.hyprland.org/Configuring/Keywords/
-- Source: ./keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("keybinds")
--################
--## AUTOSTART ###
--################
-- Source: ./autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostart")

--############################
--## ENVIRONMENT VARIABLES ###
--############################
-- Source: ./env.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("env")

--####################
--## LOOK AND FEEL ###
--####################
-- Source: ./theme.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("theme")

hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
end)
