-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local themes = "bash ~/Documents/themes/theme-switcher.sh"
local terminal = "ghostty"
local fileManager = "dolphin"
local menu = "rofi -show drun"
local powermenu = "zsh ~/.config/rofi/powermenu.sh"
local screenshot = "hyprshot -m region -m active --sclipboard-only"
local hyprlock = "hyprlock"
local killpanel = "killall waybar"
local startpanel = "waybar"

local mainMod = "SUPER"

hl.bind("ALT + C", hl.dsp.exec_cmd(themes))
hl.bind("ALT + Z", hl.dsp.exec_cmd(powermenu))
hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd(screenshot))
hl.bind("ALT + L", hl.dsp.exec_cmd(hyprlock))
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd(killpanel))
hl.bind(mainMod .. " + J", hl.dsp.exec_cmd(startpanel))

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
hl.bind(mainMod .. " + return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + backspace", hl.dsp.exit())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
--bind = $mainMod, P, pseudo, # dwindle
--bind = $mainMod, J, togglesplit, # dwindle

-- Change monitor focus
hl.bind(mainMod .. " + left", hl.dsp.focus({ monitor = "+1" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ monitor = -1 }))

-- Change window focus
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

package.path = package.path .. ";./?.lua;./?/init.lua"
local smw = require("plugins.split-monitor-workspaces")
-- Switch workspaces with mainMod + [0-9]

smw.setup({
	workspace_count = 10,
})

for i = 1, smw.get_amount_of_workspaces() do
	local n = tostring(i)
	if n == "10" then
		n = "0"
	end
	-- Switch to the Nth workspace on the currently focused monitor.
	hl.bind(mainMod .. " +" .. n, smw.workspace(n))
	-- Move the active window to the Nth workspace on the currently focused monitor silently (no focus change).
	hl.bind(mainMod .. " + SHIFT +" .. n, smw.move_to_workspace_silent(n))
end

-- move active workspace between monitors
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- Laptop multimedia keys for volume and LCD brightness
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Custom Remaps
--caps = overload(esc, SUPER)

--############
--## INPUT ###
--############

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "grp:ctrl_space_toggle",
		kb_rules = "",
		accel_profile = "flat",
		follow_mouse = 1,
		sensitivity = 0.8,
		repeat_rate = 50,
		repeat_delay = 200,
		touchpad = {
			natural_scroll = false,
		},
	},
})
