-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60",
    position = "3840x0",
    scale = "1",
})

