-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.curve("winIn", { type = "bezier", points = { { 0.1, 1.0 }, { 0.1, 1.0 } } })
hl.curve("winOut", { type = "bezier", points = { { 0.1, 1.0 }, { 0.1, 1.0 } } })
hl.curve("smoothOut", { type = "bezier", points = { { 0.5, 0 }, { 0.99, 0.99 } } })
hl.curve("layerOut", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.animation({
	leaf = "windowsIn",
	enabled = true,
	speed = 7,
	bezier = "winIn",
	style = "slide",
})
hl.animation({
	leaf = "windowsOut",
	enabled = true,
	speed = 3,
	bezier = "smoothOut",
	style = "slide",
})
hl.animation({
	leaf = "windowsMove",
	enabled = true,
	speed = 7,
	bezier = "winIn",
	style = "slide",
})
hl.animation({
	leaf = "workspacesIn",
	enabled = true,
	speed = 8,
	bezier = "winIn",
	style = "slide",
})
hl.animation({
	leaf = "workspacesOut",
	enabled = true,
	speed = 8,
	bezier = "winOut",
	style = "slide",
})
hl.animation({
	leaf = "layersIn",
	enabled = true,
	speed = 10,
	bezier = "winIn",
	style = "slide",
})
hl.animation({
	leaf = "layersOut",
	enabled = true,
	speed = 3,
	bezier = "layerOut",
	style = "popin 50%",
})

hl.config({
	general = {
		gaps_in = 10,
		gaps_out = 20,
		border_size = 3,
		col = {
			active_border = { colors = { "rgba(fab387ff)", "rgba(fab387ff)" }, angle = 45 },
			inactive_border = "rgba(00000000)",
		},
		resize_on_border = false,
		allow_tearing = false,
		layout = "dwindle",
	},
	decoration = {
		rounding = 10,
		active_opacity = 1,
		inactive_opacity = 0.8,
		shadow = {
			enabled = true,
			range = 10,
			render_power = 1000,
			color = "rgba(fab387ff)",
			color_inactive = "rgba(00000000)",
		},
		blur = {
			enabled = true,
			size = 1,
			passes = 5,
			vibrancy = 0.1696,
		},
	},
	animations = {
		enabled = false,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		new_status = "master",
	},
	misc = {
		force_default_wallpaper = -1,
		disable_hyprland_logo = false,
	},
	--#############################
	--## WINDOWS AND WORKSPACES ###
	--#############################
})

hl.on("hyprland.start", function()
	hl.exec_cmd("hyprctl setcursor hypr-dots-peach 24")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'hypr-dots-peach' &> /dev/null")
end)
